dist: trusty
language: python
python: 3.4
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
install:
  - pip install -r requirements.txt
env:
  - feature_schema: "historical_features_daily_month"
  - entity_id: "officer_id"
script: py.test -vvv -s -x --cov=webapp
after_success: codecov
