---
pct:
    - 0.01
    - 0.10
    - 0.25
    - 0.50
    - 1.0
    - 5.0
    - 10.0
    - 25.0
    - 50.0
    - 75.0
    - 100.0
abs:
    - 10
    - 50
    - 100
    - 200
    - 500
    - 1000
parameterized:
    - precision
    - recall
    - true positives
    - true negatives
    - false positives
    - false negatives
unparameterized:
    - auc
